# Machine Learning All Algorithms SKlearn 

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('iris.data.csv')

In [3]:
dataset.head(10)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa
8  4.9  3.1  1.5  0.1  Iris-setosa
9  5.4  3.7  1.5  0.2  Iris-setosa

In [13]:
x=dataset.iloc[:, 1:4].values

In [14]:
y=dataset.iloc[:,4].values


In [15]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder_y =LabelEncoder()
y =LabelEncoder_y.fit_transform(y)

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test =train_test_split(x,y,test_size=0.2)

In [18]:
# LogisticRegression Algorithem 
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(x_train , y_train)

LogisticRegression()

In [19]:
y_pred = logmodel.predict(x_test)
y_pred

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [20]:
y_test

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[13,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 11]], dtype=int64)

In [23]:
# LogisticRegression Algorithem Acuranssi
30/30

1.0

In [25]:
# navebase algorithums
from sklearn.naive_bayes import GaussianNB
classifier_np=GaussianNB()
classifier_np.fit(x_train , y_train)

GaussianNB()

In [26]:
y_pred =classifier_np.predict(x_test)
y_pred

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [27]:
y_test

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred , y_test)

array([[13,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 11]], dtype=int64)

In [32]:
# SVC algorithum kernel 'Linear'
from sklearn.svm import SVC
classifier_svc_linear=SVC(kernel='linear')
classifier_svc_linear.fit(x_train , y_train)

SVC(kernel='linear')

In [33]:
y_pred =classifier_svc_linear.predict(x_test)
y_pred

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 2, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [35]:
x_test

array([[3.4, 1.5, 0.4],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 6. , 1.8],
       [3.4, 1.5, 0.2],
       [3. , 1.1, 0.1],
       [2.9, 4.3, 1.3],
       [2.4, 3.3, 1. ],
       [2.8, 4.8, 1.4],
       [2.7, 3.9, 1.2],
       [3.3, 6. , 2.5],
       [3.1, 1.5, 0.1],
       [3. , 1.3, 0.2],
       [3. , 4.8, 1.8],
       [3. , 5.8, 1.6],
       [3.8, 6.4, 2. ],
       [3. , 5.2, 2. ],
       [2.6, 3.5, 1. ],
       [3.8, 1.7, 0.3],
       [2.9, 4.6, 1.3],
       [2.8, 6.1, 1.9],
       [3.5, 1.3, 0.3],
       [3.4, 5.6, 2.4],
       [3.6, 6.1, 2.5],
       [3.4, 5.4, 2.3],
       [2.3, 1.3, 0.3],
       [3. , 1.4, 0.1],
       [3.5, 1.6, 0.6],
       [2.6, 6.9, 2.3],
       [3.9, 1.3, 0.4]])

In [37]:
y_test

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [40]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred ,y_test)

array([[13,  0,  0],
       [ 0,  6,  1],
       [ 0,  0, 10]], dtype=int64)

In [41]:
# SVC algorithum kernel 'Linear' accurace
29/30

0.9666666666666667

In [47]:
# SVC algorithum kernel 'poly'
from sklearn.svm import SVC
classifier_svc_poly=SVC(kernel='poly')
classifier_svc_poly.fit(x_train , y_train)

SVC(kernel='poly')

In [48]:
y_pred = classifier_svc_poly.predict(x_test)
y_pred

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [49]:
y_test

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [50]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred ,y_test)

array([[13,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 11]], dtype=int64)

In [51]:
# SVC algorithum kernel 'poly' accurace
30/30

1.0

In [52]:
# SVC algorithum kernel 'sigmoid'
from sklearn.svm import SVC
clasifier_svm_sigmoid =SVC(kernel='sigmoid')
clasifier_svm_sigmoid.fit(x_train , y_train)

SVC(kernel='sigmoid')

In [55]:
y_pred =clasifier_svm_sigmoid.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1])

In [54]:
y_test

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [56]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred ,y_test)

array([[ 0,  0,  1],
       [12,  6, 10],
       [ 1,  0,  0]], dtype=int64)

In [57]:
# SVC algorithum kernel 'poly' accurace
8/30

0.26666666666666666

In [58]:
# Decision tree algorithum 
from sklearn.tree import DecisionTreeClassifier
clasifier_dt =DecisionTreeClassifier(criterion='entropy')
clasifier_dt.fit(x_train , y_train)

DecisionTreeClassifier(criterion='entropy')

In [59]:
y_pred =clasifier_dt.predict(x_test)
y_pred

array([0, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 2, 1, 0, 1, 2, 0,
       2, 2, 2, 0, 0, 0, 2, 0])

In [60]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred ,y_test)

array([[13,  0,  0],
       [ 0,  6,  1],
       [ 0,  0, 10]], dtype=int64)

In [61]:
# Decision tree algorithum 
29/30


0.9666666666666667